# Load includes
imports:
  - { resource: "EXT:uw_a11y_check/Configuration/A11y/Includes/Analyzers.yaml" }
  - { resource: "EXT:uw_a11y_check/Configuration/A11y/Includes/CheckUrlGenerators.yaml" }
  - { resource: "EXT:uw_a11y_check/Configuration/A11y/Includes/TestSuites.yaml" }

presets:
  pageContent:
    name: "Check page content elements (no plugins)"
    description: "This check renders all content elements of the given page(s) and performs the accessibility check"
    analyzer:
      id: "pageContentAnalyzer"
      configuration: {}
    checkUrlGenerator:
      id: "pageContent"
      configuration:
        targetPid: 104
        ignoreContentTypes:
          - list
    testSuite:
      id: "internalTests"
      tests:
        linkTextDenylist:
          configuration:
            denylist: ['mehr', 'details', 'hier']
        headingOrder:
          configuration:
            limitToColPos: [0]
  extNews:
    name: "Check ext:news records"
    description: "This check renders all news records of the given page(s) and performs the accessibility check"
    analyzer:
      id: "newsAnalyzer"
      configuration: {}
    checkUrlGenerator:
      id: "newsDetail"
      configuration:
        targetPid: 105
    testSuite:
      id: "internalTests"
      configuration: {}